// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using biblioteca.WEBAPI.Date;

namespace biblioteca.WEBAPI.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20220117022522_first_migration")]
    partial class first_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("biblioteca.WEBAPI.Models.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("curso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("periodo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("biblioteca.WEBAPI.Models.Bibliotecaria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dt_admissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Bibliotecarias");
                });

            modelBuilder.Entity("biblioteca.WEBAPI.Models.Emprestimo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("alunoId")
                        .HasColumnType("int");

                    b.Property<int>("bibliotecaId")
                        .HasColumnType("int");

                    b.Property<int?>("bibliotecariaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("devolucao")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("alunoId");

                    b.HasIndex("bibliotecariaid");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("biblioteca.WEBAPI.Models.Livro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtd_pg")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tema")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("biblioteca.WEBAPI.Models.Emprestimo", b =>
                {
                    b.HasOne("biblioteca.WEBAPI.Models.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("alunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("biblioteca.WEBAPI.Models.Bibliotecaria", "bibliotecaria")
                        .WithMany()
                        .HasForeignKey("bibliotecariaid");
                });
#pragma warning restore 612, 618
        }
    }
}
